### ISSUE TITLE
Required VC redist

### ISSUE THREAD

**Issue by MikkiCloud** [GregLando113/gwlauncher#10]
After resetting my computer and reinstalling Guild Wars and the GWLauncher, I had a problem where the GWLauncher would shut down immediately and not launch the GW client.  Thinking it might be AV or permissions related and after much tinkering, I realized that it is not your client, but missing VC redist package (2015) that is missing. I add this as you might want to consider adding this to your notes under the installation section.

**Comment by Explomatic** [comment]
How did you come to this conclusion? I was in the same boat yesterday - newly installed PC and could not get gwlauncher to work with the same behaviour you describe. Looking in the event log all I could find was this unexplanatory error message
```
Faulting application name: Gw.exe, version: 1.0.0.1, time stamp: 0x60108719
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x82dc99a2
Exception code: 0xc0000409
Fault offset: 0x0009d132
Faulting process ID: 0x1a5c
Faulting application start time: 0x01d724d8e973ff97
Faulting application path: D:\Guild Wars\Gw.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report ID: e8264af2-9575-44a6-8150-aa57ffa16ea0
Faulting package full name: 
Faulting package-relative application ID: 
```
I noticed I had the (new?) bundled VC redistributable installed which contains things for 2015, 2017, and 2019 (found [here](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0)) and was unable to install the 2015 specific version (found [here](https://www.microsoft.com/en-us/download/details.aspx?id=48145)). Uninstalling the bundled version and installing the specific 2015 version solved the problem for me, but I have no idea if it will become a problem later on :/ Wonder if it's an issue that can be solved in the gwlauncher or if it's Microsoft that messed something up.

**Comment by DubbleClick** [comment]
vc redistributables should not be required (for gwlauncher) anymore, but you need them to launch guild wars
