### ISSUE TITLE
Data patch makes gw crash at load finish

### ISSUE THREAD

**Issue by KevinDenis** [GregLando113/gwlauncher#12]
GWLaucher version r11.
When enabling the data path functionality, gw crashes when the map is just finished loading.

**Comment by chichke** [comment]
Same here did you find anything ?

**Comment by BearsMan** [comment]
Running the dat patch has massive side effects

**Comment by DubbleClick** [comment]
.dat fix always had side effects and it is explicitly mentioned to not use this feature unless you absolutely must run multiple clients off one installation
