### ISSUE TITLE
Do not run as privileged user

### ISSUE THREAD

**Issue by matlink** [GregLando113/gwlauncher#13]
Is it possible not to run it as privileged user by default? It looks like it does not require such permissions for daily usage.

**Comment by DubbleClick** [comment]
Agreed, this is fairly bothersome since it breaks ShareX and other programs ability to intercept keyboard inputs.

**Comment by DubbleClick** [comment]
#15 I've created a preliminary solution to at least have the gw executable run unelevated.

**Comment by DubbleClick** [comment]
this has long been implemented
