### ISSUE TITLE
r11 starts all the clients but they crash

### ISSUE THREAD

**Issue by gwmai** [GregLando113/gwlauncher#17]
When using version r11, all clients start up correctly however after 1-2 minutes one by one they start crashing. What info can I provide to determine what's causing the crash?

Best regards

**Comment by gwmai** [comment]
I've tried to build latest version from source and see if the problem persists. The games are not crashing instantly with the dev version however certain actions cause a game crash. For example, 

- click on change district -> internation = crash
- click on change district -> more options = working
- open hero / title panel = crash 

I'm not sure what the problem is.

**Comment by DubbleClick** [comment]
this has absolutely nothing to do with gwlauncher, unless you enabled .dat fix
please disable .dat fix
