### ISSUE TITLE
Missing r12 release?

### ISSUE THREAD

**Issue by MangelMaxime** [GregLando113/gwlauncher#18]
Hello,

there seems to be missing a r12 release/tag on the repo [release list](https://github.com/GregLando113/gwlauncher/releases)

[r12 commit](https://github.com/GregLando113/gwlauncher/commit/be94e146d9781fbb5865f004447989b9aa03b9f5)

I am pointing it out in case the r12 was containing some fixes that people should have.

**Comment by DubbleClick** [comment]
it's on my fork but yeah it should probably get tagged here too
