### ISSUE TITLE
r12 release download file? Some help to users of r11 release

### ISSUE THREAD

**Issue by Richard-G4WKW** [GregLando113/gwlauncher#19]
As posted by someone else, the r12 download zip file is still not listed for download.

I got everything working fine with the r11 release, but can understand why lots of people have made comments on your YouTube page for the video, which really needs updating, if you have chance.

https://www.youtube.com/watch?v=ir4__aInJKE

I have made a detailed comment, explaining to people how to install and run it, which hopefully is helpful.  Please see that for information which (hopefully) is all ok?  My comment is listed under "Richard G4WKW" this morning.

PS:  It would be really helpful if your launcher used the account name as the window title (as appeared to be the case when you made your video), with the r11 release, each window has "Guild Wars" in the title, which is not so helpful.  It is not essential, but nice if you can still do that.

**Comment by DubbleClick** [comment]
it was under a different repository that is now merged here
