### ISSUE TITLE
New Guild Wars Crashes with "Apply .dat Patch" checkbox on (checked)

### ISSUE THREAD

**Issue by Richard-G4WKW** [GregLando113/gwlauncher#20]
I am now disappointed after using your launcher successfully several times earlier this morning.  

The Launcher still works fine when the "Apply .dat Patch" checkbox is OFF (unchecked), but whenever I put it ON, then Guild Wars crashes when I attempt to load that account.  

The series of events are:

1) Run GW Launcher
2) Open GW Launcher from the system tray
3) Double-click or right-click and select "Launch Selected" for the account
4) Guild Wars launches, logs in and takes me to the character select screen
5) I select a character and click the "Play" button
6) The loading screen for the character's location comes up, but then the game immediately crashes and the crash dialog is presented (I have copied the log to a file and will attach it).

Things that I have noticed
--------------------------

When the character select screen is loaded, the last used character is not shown, always the same one.  Does this appear to show that perhaps a cached version of the Gw.dat file might be being used by the launcher?  If I:

A) Load Guild Wars using the standard shortcut, rather than using the GW Launcher:
(1) load the account via the normal shortcut, 
(2) load a different character
(3) log out using "change char" (the character I last used is shown)
(4) x out of guild wars
(5) load guild wars again, the character I changed to (and last loaded) is shown in the character select screen.

B) When I do the identical steps, as in A) above, when launching from the GW Launcher, the same (Character name added to the launcher) character is always shown in step (5), not the last one I used for that account.

Things that I have tried
------------------------

1) Rebooted my PC (it is running the latest edition of Windows 10 Pro)
2) Ran Guild Wars with the -debug switch both from the shortcut and via the GW Launcher and everything is fine in both cases.
3) Forced download of latest updates using -image switch.

It is rather annoying, as everything was working perfectly early today and I was running 3 accounts simultaneously using your GW Launcher.   The problem first happened after I added 3 more accounts, giving a total of 6 accounts in the launcher.  I removed four of the accounts, leaving just the first two that I added,  but that has not helped.

CrashReport
------------

I will attach the file, but main bit is in the first few lines:

*--> Crash <--*
Exception: c0000005 
Memory at address 00000210 could not be read
App: Gw.exe

[crash_report.txt](https://github.com/GregLando113/gwlauncher/files/5340059/crash_report.txt)

I might try some other stuff, but it makes little sense to me why it was working perfectly earlier today, but now does not do so?  I must be missing something somewhere perhaps?

**Comment by BearsMan** [comment]
@Richard-G4WKW its best not to use the dat patch since their side effects to it u wont be able to save templates, if u crash u dont get an option to re connect u cant save screenshots u have taken etc

it is all explained well in this video: https://www.youtube.com/watch?v=ir4__aInJKE&ab_channel=KAOSTheory

**Comment by sndcode** [comment]
ive noticed this too plus a couple other stuff . i will fork this repo and fix that and make a request . 
The launcher is great but its way to rough in its usage also passwords will be encoded in my fork

**Comment by DubbleClick** [comment]
.dat Patch has been discontinued and removed due to the issues it had. if you need multiple accounts running at the same time you'll have to trade the 4gb of disk space
