### ISSUE TITLE
Issues with plugins folder using version 12.

### ISSUE THREAD

**Issue by Galygious** [GregLando113/gwlauncher#27]
using version 12 couldn't figure out how to launch gwtb++ with dll in folder. went to version 11 and instantly worked.

**Comment by DubbleClick** [comment]
I'll take a look and fix this soon, might not get umod support included in that time though

**Comment by DubbleClick** [comment]
A new release fixing this has been tagged under: https://github.com/GregLando113/gwlauncher/releases/tag/r12.1
