### ISSUE TITLE
GW.Launcher Will not load.

### ISSUE THREAD

**Issue by SentaiBrad** [GregLando113/gwlauncher#29]
I have the launcher exe in my GW1 folder, it is not installed on my C drive at all, running via Windows 11 and the game runs just fine otherwise. I've tried Run As Admin and Compatability Modes going back to W7 (though the last update was recently so I don't think that is needed). 

Is there an FAQ I missed? Is there anything else I can do to get this launcher to work? Thank you ahead of time.

**Comment by DubbleClick** [comment]
If you're using r12+, you need .NET 6 installed.
I will add that to the FAQ at some point.

https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by SentaiBrad** [comment]
Sadly, installing both the 64bit and 32bit binaries did not resolve the issue.

**Comment by DubbleClick** [comment]
Unfortunately it seems like the publish profile had bugged out. There will be a release tagged soon - use r12 in the meantime. Sorry!

**Comment by SentaiBrad** [comment]
Hey, no worries at all. I understand completely. Hopefully, if others are having issues they see this then.

**Comment by DubbleClick** [comment]
A new release fixing this has been tagged under: https://github.com/GregLando113/gwlauncher/releases/tag/r12.1
