### ISSUE TITLE
r12.1 not launching

### ISSUE THREAD

**Issue by Chromos-Def** [GregLando113/gwlauncher#31]
https://github.com/GregLando113/gwlauncher/releases/tag/r12.1
is having this issue.

![image](https://user-images.githubusercontent.com/47635128/162127116-96993195-a8e5-450c-92b8-5fd59b32ca64.png)

**Comment by DubbleClick** [comment]
See, it tells you what exactly you have to do to run it. If you do not wish to install .NET 6, you can download the self-contained version under releases instead.

**Comment by Chromos-Def** [comment]
Ah, I should've highlighted that I have .NET 6 on that add/remove programs window behind my file explorer there.

**Comment by DubbleClick** [comment]
You need the desktop runtime (x86) as highlighted in the error message. Alternatively, use https://github.com/GregLando113/gwlauncher/releases/download/r12.1/GW_Launcher_self-contained.exe

**Comment by Chromos-Def** [comment]
That's my fault. I thought the bare minimum runtimes would cover any .net app that's been built upon it.

**Comment by DubbleClick** [comment]
Unfortunately not. The good news is that the Desktop Runtimes are a strict superset of the base runtimes. You do not need to install both, the Desktop Runtime covers everything.
