### ISSUE TITLE
Missing Frameworks

### ISSUE THREAD

**Issue by ColeSpringer** [GregLando113/gwlauncher#46]
When trying to use the launcher I get an error that claims there are missing frameworks for .NET. When I click yes to download the error closes but nothing is downloaded and the problem occurs again when using the launcher.

I am using windows 11 and the non steam version of guild wars. I have also downloaded and installed .NET 6 x86 and x64.

![Screenshot 2022-07-12 170000](https://user-images.githubusercontent.com/93888664/178594698-96f090dc-c5c5-4b19-951e-fea5ac54ceaf.png)

![Screenshot 2022-07-12 170032](https://user-images.githubusercontent.com/93888664/178594699-ecbd6952-9dbe-4f05-9774-b27430ca358e.png)

**Comment by ColeSpringer** [comment]
I fixed the issue by downloading the Desktop Runtime version. The readme only states you need the Runtime version so that is what I downloaded originally.

**Comment by DubbleClick** [comment]
The readme states that the .NET 6 Desktop Runtime (x86) is required. The popup when you launch it without any .NET 6 installed also says the same.

It's unfortunate that it doesn't link to the direct download page, but that's unfortunately outside of our control. Maybe Microsoft will change it in the future.

**Comment by DubbleClick** [comment]
https://github.com/dotnet/runtime/issues/36765
