### ISSUE TITLE
Any way to make this use Steam so it can help track Game hours and also take screenshots?

### ISSUE THREAD

**Issue by Grulagz** [GregLando113/gwlauncher#48]
Hi team, Loving this, it's such a great tool for GW..

Any way to make this use Steam so it can help track Game hours and also take screenshots?

That's the only thing missing, sadly.. If there was a way to somehow hook Steam, optionally so the overlay, screenshots and tracking of game hours works, this would be so much better!!!

Thanks heaps

**Comment by DubbleClick** [comment]
I'm not sure if this is even possible - I can't find any information on injecting the steam overlay with external launchers. If it's just a matter of injecting a dll, you can create a shortcut to that and place it in the plugins folder.

**Comment by DubbleClick** [comment]
If you want the overlay, create a shortcut to `"C:\Program Files (x86)\Steam\GameOverlayRenderer.dll"` and put that shortcut in your plugins folder.

**Comment by Grulagz** [comment]
> If you want the overlay, create a shortcut to `"C:\Program Files (x86)\Steam\GameOverlayRenderer.dll"` and put that shortcut in your plugins folder.

Oh cool, thanks for that!

It's more that when running Guild Wars in Steam it basically does something to make it count as 'being played' which also then tracks the hours, as well as the overlay enabled.
![steam_cKpUffxnYC](https://user-images.githubusercontent.com/106040813/187417536-992a2193-90b5-4170-bfd6-cccc7f940ee4.png)


I am wanting the features/function of this tool in the way it loads mods, but trying to get it to launch via steam for tracking the hours etc.

I found this when editing the steam shortcut placed to desktop with notepad;

![notepad++_oTBxfQyDc2](https://user-images.githubusercontent.com/106040813/187418804-fd891dc6-e459-4f01-a5b7-3b8fca684334.png)

I don't know if that's of any use or insight, and i am probably going way off-course from the possibilities here, i just thought i'd ask, even if it's a long-shot.

Anyway thanks for the tool and your help,

**Comment by DubbleClick** [comment]
That part doesn't work for me even if I launch gw through steam, so I cannot check that.

Unfortunately steam is *extremely* scarce with their information on how to embed the overlay from another process, I've read that setting an environment variable SteamGameId for the process and then injecting GameOverlayRenderer.dll should work, but I cannot verify that.

For me, the steam app id for my guild wars (added as non steam game) is `16260156758557720576`. Guild Wars Trilogy on Steam is `29620`. For you it's `29720`. I can't make much sense of that. Did you buy the game through steam?

**Comment by Grulagz** [comment]
> 

Huh pretty interesting.. I think the app id might be related to the history of different 'versions' coming out. If i can recall there was an original 'guild wars', then there was a 'Trilogy' version

https://store.steampowered.com/app/29570/Guild_Wars_Trilogy/

I guess the original got taken off of steam, because clicking the Store on the game goes to the steam homepage..

Strangely enough it actually lets me run the Trilogy too, even though it's listed in my DLC..

What's weird is it seems to have its own independent playtime, separate from the version in my steam games list.

![steam_4Nm0XnhyeN](https://user-images.githubusercontent.com/106040813/187423138-787e7a5e-b7bd-4d12-b94c-19809f1d9083.png)

They both seem to run though. Taking a screenshot shows up in 29720's folder, so i presume it somehow counts the trilogy as the original game for me, and it still shows the same playtime in steam when i run it.

Lol what a rabbit-hole!
![steam_Ue9WlM69s3](https://user-images.githubusercontent.com/106040813/187423789-8fb3ad09-7c48-414d-bbd2-117babd4b88c.png)


All good, it is what it is! I'll just use the GW Launcher, i guess steam playtime isnt that important, /age shows play time anyway, afterall. And i can take screenshots though the .dll overlay thing you mentioned, which is great. Thanks!

**Comment by DubbleClick** [comment]
If you happen to have Visual Studio installed, you could try cloning the project and putting
`Environment.SetEnvironmentVariable("SteamGameId", "29720");` somewhere at the start of main().

This should in theory make steam register that the game is running once you launch an instance.
