### ISSUE TITLE
Launcher won't launch without very specific .net version

### ISSUE THREAD

**Issue by Sudwood** [GregLando113/gwlauncher#50]
While trying to get the launcher to work I went through every version of .net 6 available on the microsoft website and the only version that works for me is 6.0.2 which is not the version linked when you first run the launcher. Event viewer gave the following error when the program crashed using any other version of .net:
> Application: GW_Launcher.exe
> CoreCLR Version: 6.0.21.52210
> .NET Version: 6.0.0
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.IO.FileLoadException: Could not load file or assembly 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, > PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
> File name: 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
>    at GW_Launcher.Program.Main()

**Comment by DubbleClick** [comment]
Ah, the beauty of Microsoft. 

However, the x86 Desktop Runtime (as specified in the readme) that the launcher first links to does work.

**Comment by Sudwood** [comment]
6.0.8 x86 was not launching for me using windows 11 originally but now that I have updated from 6.0.2 to 6.0.8 it is now working so I am just going to chuck that up to microsoft. Thank you for the quick response!

**Comment by DubbleClick** [comment]
That's a little weird, since I actually built it with 6.0.2 sdk O.o

**Comment by Sudwood** [comment]
Who knows? They might have missed one library with the  6.0.8 install, probably just weirdness

**Comment by DubbleClick** [comment]
I think you had 6.0.0 installed previously as indicated in the error. I would target it, but unfortunately not possible due to the winforms bug. Thanks for bringing it to my attention though, I should specify it in the readme.

**Comment by Sudwood** [comment]
No thats no problem Looking through my event viewer it seems my (possibly broken) install of win 11 was not recognizing any installation of the 32bit .net 6 until I installed 6.0.0 then after updating to 6.0.2 it worked and now updating to 6.0.8 it also works. It is likely it was always a windows problem
