### ISSUE TITLE
Window positioned off-screen in multi-monitor setup

### ISSUE THREAD

**Issue by roy-harmon** [GregLando113/gwlauncher#58]
When using multiple monitors stacked vertically, the GW Launcher window is displayed with most of the window off-screen. This is because the SystemInformation.VirtualScreen considers all monitors together, but Cursor.Position does not. For example, with two 1920x1080 screens arranged vertically, SystemInformation.VirtualScreen.Height would be 2160, but if the lower screen is primary and the cursor is at the bottom edge (as when clicking an icon on the taskbar), the Cursor.Position.Y would be 1080. This affects the positioning calculations, causing the window to be mostly off-screen.

**Comment by DubbleClick** [comment]
Thanks, will do a release fairly soon.

**Comment by andrinalaurel** [comment]
Hi I updated and this issue persists. Please advise.
