### ISSUE TITLE
Not launching .dll .tpf files

### ISSUE THREAD

**Issue by jotacuatro** [GregLando113/gwlauncher#64]
It's working in one of my computers but not launching .dll and .tpf in other one.
Any clue of what can it be? I have the "plugins" folders on both. Do I need anything more than dotnet 6.0.16 win x86??
Thx

**Comment by DubbleClick** [comment]
Is the gw window that's opened closing and then reopening? Your gw most likely failed to properly update itself. Delete the .exe and run the gw installer again, then copy the new gw.exe file to all your folders.

**Comment by roy-harmon** [comment]
> Is the gw window that's opened closing and then reopening? 

I've noticed that mine has been doing that for two out of three accounts, leading to only one window with the account name as the title (on the WIndows 10 taskbar, I mean) and two just called "Guild Wars". Unfortunately, copying the Gw.exe file from the "working" one didn't fix the other two. I would try running the GW installer again, but the last time I did that, I ran into "unable to create folder" problems when launching a second client. I don't know what's going on, but I'm pretty sure it's a configuration issue on my end. Maybe there's another file I need to copy; I'll have to look into it further.

Side tangent related to DLLs: I was able to get the DirectSong music (and customized playlist) to play in-game on Windows 10 by copying the "wmvcore.dll" file from an old WIndows 7 installation to each GW program folder (the same directory as the Gw.exe file for each account). For reference, the Win7 file I used was file version 11.0.6000.6351.
I also managed to re-enable the "Use 3D audio hardware" and "Use EAX" options using [dsoal-GW1](https://github.com/ChthonVII/dsoal-GW1) by copying the files to each of the GW program folders I'm using _and_ specifying "-dsound" in the "Ex Args" field for the respective accounts in GW Launcher. 
So, here's confirmation that both DirectSong and DSOAL-GW1 are compatible with GW Launcher, provided that these steps are taken.

**Comment by jotacuatro** [comment]
It's charging the game for me but without the .dll or .pf files. And I have reinstalled everything but nothing happens it goes to the same. Maybe it's something from hardware... but I think everything is updated, so I don't know if there is another thing that I need, because in other computers it's everything ok for me. The GW is working fine, it's only that I miss to charge the .dll and .tpf files.

**Comment by jotacuatro** [comment]
The .dll and .tpf I'm using are:
Borderless Cartography Made Easy 2015 1.3.tpf
Dark_Glass_Beta_5.tpf
GWToolboxdll.dll

**Comment by DubbleClick** [comment]
> I don't know what's going on, but I'm pretty sure it's a configuration issue on my end. Maybe there's another file I need to copy; I'll have to look into it further.

@roy-harmon no, this is always related to non up-to-date gw.exes. The "unable to create folder" is not related to reinstalling gw.

@jotacuatro please read my reply. I didn't ask whether GW was opening at all, I asked if it spawned a loading window that then closed and reopened. This is 99.9999999999999999999999999999% the issue and once again, related to gw.exe not being up to date.

**Comment by jotacuatro** [comment]
No... it's not doing this. Just open GW without the .dll and .tpf things. Tried to open this in admind. i'm trying to reinstall everything from 0 again

**Comment by jotacuatro** [comment]
I have no spawning loading window closing and reopening...  Checking some other things

**Comment by DubbleClick** [comment]
If you are entirely sure of that, I cannot help you. There's nothing in gwlauncher that is OS specific and all dependencies are bundled.
