### ISSUE TITLE
Cant open more than one client

### ISSUE THREAD

**Issue by Lemaggo** [GregLando113/gwlauncher#67]
Hey, I downloaded the latest version. 
Before that everything was running smoothly and there were no problems.
Unfortunately, now I can only open one client. 
I do see that my pc tries to load when I click on a 2nd one, but nothing happens after that. 
The account is also only briefly active and then jumps back to inactive.

Can you help me there? Or have I overlooked something? 

Many thanks in advance

**Comment by DubbleClick** [comment]
Sounds like gw isn't properly updated. Copy your main gw.exe to all the copied folders.

**Comment by Lemaggo** [comment]
First of all, thank you for the quick feedback. 

I have done, but unfortunately still the same problem. 

As soon as I want to start the 2nd client, it loads for a fraction of a second and then apparently closes again. 

Doesn't the game update itself automatically at every start?

Thank you for your help

**Comment by DubbleClick** [comment]
It occasionally fails to update fully, leaving gw in a state where at every launch it opens a loading window for a fraction, updates, closes and then opens up again. When you already have an instance running, it will open, fail to update, close and not open again.

If the main gw.exe isn't fully up to date you can delete it and run the installer from the website again. It only takes a second as your .dat is still there.

**Comment by Lemaggo** [comment]
That worked, thanks a thousand for your help
