### ISSUE TITLE
Window placement after starting

### ISSUE THREAD

**Issue by farkmi** [GregLando113/gwlauncher#7]
The window seems to be statically placed above the taskbar icon, and doesn't save its position after quitting either. This leads to the launcher effectively being unusable when the taskbar is positioned on the top edge of the screen, as the window is placed outside of the visible area. 

Suggestion: have a fallback position (i.e. in the middle of the screen) where the window is drawn in case the titlebar would be situated outside of the desktop edges.

**Comment by EnergyAura** [comment]
I second this change. I position my taskbar at the top of my screen (always have) and its annoying to move the taskbar to run the program. Seems like an easy fix to me.
