### ISSUE TITLE
Blish icon occupies Black Lion icon space on reinstall

### ISSUE THREAD

**Issue by Kawsmecal** [GregLando113/gwlauncher#71]
Had to reinstall Blish with GWlauncher when making some changes and everything is setup the way it's told to before as I followed the same guide, but it seems that Blish isn't moving over to make room for the new Wizard Vault icon that was added so now they occupy the same spot as the trading post/gem store icon button.

**Comment by BearsMan** [comment]
I think you are talking about GW2, GwLaucher is only used for GW1

**Comment by Kawsmecal** [comment]
Whoops idk how I got here I was in gw2launcher I am not paying attention
